MEDIA_PATH="./media"
SLOWED_BASENAME="slowed"
GIF_BASENAME="gifs"
VIDEO_BASENAME="videos"
AUDIO_BASENAME="audio"
PLAYLIST_ID = "37i9dQZEVXbMDoHDwVN2tF"

# slowed with reverb settings:
ROOM_SIZE=0.75
DAMPING=0.25
WET_LEVEL=0.12
DRY_LEVEL=0.2
DELAY=0.5
SLOWFACTOR=0.15